//! Host-side splat export and import utilities (PLY and binary .splat).
#![allow(clippy::too_many_arguments)]

#[cfg(feature = "gpu")]
use std::fs::File;
#[cfg(feature = "gpu")]
use std::io::{BufWriter, Write};
#[cfg(feature = "gpu")]
use std::path::Path;

#[cfg(feature = "gpu")]
use crate::sh::{rgb_to_sh0_value, sh_coeff_count_for_degree};
use thiserror::Error;

#[derive(Debug, Clone, PartialEq)]
pub struct SplatMetadata {
    pub iterations: usize,
    pub final_loss: f32,
    pub gaussian_count: usize,
    /// SH degree used for the scene (0 = RGB only, 1-3 = SH coefficients).
    pub sh_degree: usize,
}

impl Default for SplatMetadata {
    fn default() -> Self {
        Self {
            iterations: 0,
            final_loss: 0.0,
            gaussian_count: 0,
            sh_degree: 0,
        }
    }
}

#[derive(Debug, Error)]
pub enum SceneIoError {
    #[error("failed to write scene {path}: {source}")]
    Write {
        path: String,
        source: std::io::Error,
    },
    #[error("failed to read scene {path}: {source}")]
    Read {
        path: String,
        source: std::io::Error,
    },
    #[error("invalid scene format: {message}")]
    InvalidFormat { message: String },
    #[error("parse error: {0}")]
    Parse(String),
}

#[cfg(feature = "gpu")]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum PlyOpacityRepresentation {
    Probability,
    RawLogit,
}

#[cfg(feature = "gpu")]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum PlyShCoeffLayout {
    Interleaved,
    ChannelMajor,
}

#[cfg(feature = "gpu")]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum PlyFormat {
    Ascii,
    BinaryLittleEndian,
}

#[cfg(feature = "gpu")]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum SplatFileFormat {
    Ply,
    Splat,
}

/// Fidelity guarantees provided by a scene artifact format.
#[cfg(feature = "gpu")]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SplatArtifactFidelity {
    /// Preserves all Gaussian parameters, SH coefficients, and training metadata.
    Lossless,
    /// Legacy 32-byte rows with quantized RGB, opacity, and rotation and no metadata.
    LossyLegacy,
}

#[cfg(feature = "gpu")]
#[derive(Debug)]
struct ParsedPlyHeader {
    format: PlyFormat,
    vertex_count: usize,
    vertex_properties: Vec<String>,
    opacity_representation: Option<PlyOpacityRepresentation>,
    sh_coeff_layout: Option<PlyShCoeffLayout>,
    metadata: SplatMetadata,
    has_explicit_sh_degree: bool,
}

#[cfg(feature = "gpu")]
#[derive(Debug)]
struct VertexFieldMap {
    positions: [usize; 3],
    log_scales: [usize; 3],
    rotations: [usize; 4],
    opacity: usize,
    sh_dc: [usize; 3],
    sh_rest: Vec<usize>,
}

#[cfg(feature = "gpu")]
fn write_ply_header<W: Write>(
    writer: &mut W,
    path: &Path,
    metadata: &SplatMetadata,
    vertex_count: usize,
    sh_rest_count: usize,
) -> Result<(), SceneIoError> {
    writeln!(writer, "ply").map_err(|source| SceneIoError::Write {
        path: path.display().to_string(),
        source,
    })?;
    writeln!(writer, "format ascii 1.0").map_err(|source| SceneIoError::Write {
        path: path.display().to_string(),
        source,
    })?;
    writeln!(writer, "comment Generated by RustGS").map_err(|source| SceneIoError::Write {
        path: path.display().to_string(),
        source,
    })?;
    writeln!(writer, "comment iterations {}", metadata.iterations).map_err(|source| {
        SceneIoError::Write {
            path: path.display().to_string(),
            source,
        }
    })?;
    writeln!(writer, "comment final_loss {}", metadata.final_loss).map_err(|source| {
        SceneIoError::Write {
            path: path.display().to_string(),
            source,
        }
    })?;
    writeln!(writer, "comment sh_degree {}", metadata.sh_degree).map_err(|source| {
        SceneIoError::Write {
            path: path.display().to_string(),
            source,
        }
    })?;
    writeln!(writer, "comment opacity_representation raw_logit").map_err(|source| {
        SceneIoError::Write {
            path: path.display().to_string(),
            source,
        }
    })?;
    writeln!(writer, "comment sh_coeff_layout channel_major").map_err(|source| {
        SceneIoError::Write {
            path: path.display().to_string(),
            source,
        }
    })?;
    writeln!(writer, "element vertex {}", vertex_count).map_err(|source| SceneIoError::Write {
        path: path.display().to_string(),
        source,
    })?;
    for property in [
        "x", "y", "z", "nx", "ny", "nz", "f_dc_0", "f_dc_1", "f_dc_2",
    ] {
        writeln!(writer, "property float {property}").map_err(|source| SceneIoError::Write {
            path: path.display().to_string(),
            source,
        })?;
    }
    for i in 0..sh_rest_count {
        writeln!(writer, "property float f_rest_{i}").map_err(|source| SceneIoError::Write {
            path: path.display().to_string(),
            source,
        })?;
    }
    for property in [
        "opacity", "scale_0", "scale_1", "scale_2", "rot_0", "rot_1", "rot_2", "rot_3",
    ] {
        writeln!(writer, "property float {property}").map_err(|source| SceneIoError::Write {
            path: path.display().to_string(),
            source,
        })?;
    }
    writeln!(writer, "end_header").map_err(|source| SceneIoError::Write {
        path: path.display().to_string(),
        source,
    })?;
    Ok(())
}

#[cfg(feature = "gpu")]
fn opacity_to_logit(opacity: f32) -> f32 {
    let clamped = opacity.clamp(1e-6, 1.0 - 1e-6);
    (clamped / (1.0 - clamped)).ln()
}

#[cfg(feature = "gpu")]
fn splat_file_format(path: &Path) -> Result<SplatFileFormat, SceneIoError> {
    match path
        .extension()
        .and_then(|extension| extension.to_str())
        .map(|extension| extension.to_ascii_lowercase())
        .as_deref()
    {
        Some("ply") => Ok(SplatFileFormat::Ply),
        Some("splat") => Ok(SplatFileFormat::Splat),
        Some(extension) => Err(SceneIoError::InvalidFormat {
            message: format!(
                "unsupported splat output extension '.{extension}'; expected .splat or .ply"
            ),
        }),
        None => Err(SceneIoError::InvalidFormat {
            message: "missing splat output extension; expected .splat or .ply".to_string(),
        }),
    }
}

/// Return the documented fidelity contract for a supported splat artifact extension.
#[cfg(feature = "gpu")]
pub fn splat_artifact_fidelity(path: &Path) -> Result<SplatArtifactFidelity, SceneIoError> {
    match splat_file_format(path)? {
        SplatFileFormat::Ply => Ok(SplatArtifactFidelity::Lossless),
        SplatFileFormat::Splat => Ok(SplatArtifactFidelity::LossyLegacy),
    }
}

#[cfg(feature = "gpu")]
fn opacity_value_to_logit(value: f32, representation: PlyOpacityRepresentation) -> f32 {
    match representation {
        PlyOpacityRepresentation::Probability => opacity_to_logit(value),
        PlyOpacityRepresentation::RawLogit => value,
    }
}

#[cfg(feature = "gpu")]
fn interleaved_sh_rest_to_channel_major(values: &[f32]) -> Vec<f32> {
    let coeffs_per_channel = values.len() / 3;
    let mut reordered = Vec::with_capacity(values.len());
    for channel in 0..3 {
        for coeff_idx in 0..coeffs_per_channel {
            reordered.push(values[coeff_idx * 3 + channel]);
        }
    }
    reordered
}

#[cfg(feature = "gpu")]
fn channel_major_sh_rest_to_interleaved(values: &[f32]) -> Vec<f32> {
    let coeffs_per_channel = values.len() / 3;
    let mut reordered = Vec::with_capacity(values.len());
    for coeff_idx in 0..coeffs_per_channel {
        for channel in 0..3 {
            reordered.push(values[channel * coeffs_per_channel + coeff_idx]);
        }
    }
    reordered
}

#[cfg(feature = "gpu")]
fn parse_ply_header(bytes: &[u8], path: &Path) -> Result<(ParsedPlyHeader, usize), SceneIoError> {
    let mut offset = 0usize;
    let mut saw_magic = false;
    let mut current_element: Option<String> = None;
    let mut header = ParsedPlyHeader {
        format: PlyFormat::Ascii,
        vertex_count: 0,
        vertex_properties: Vec::new(),
        opacity_representation: None,
        sh_coeff_layout: None,
        metadata: SplatMetadata::default(),
        has_explicit_sh_degree: false,
    };

    while offset < bytes.len() {
        let line_end = bytes[offset..]
            .iter()
            .position(|&byte| byte == b'\n')
            .map(|relative| offset + relative + 1)
            .unwrap_or(bytes.len());
        let raw_line = &bytes[offset..line_end];
        offset = line_end;

        let trimmed = std::str::from_utf8(raw_line)
            .map_err(|err| SceneIoError::Parse(err.to_string()))?
            .trim();

        if !saw_magic {
            if trimmed != "ply" {
                return Err(SceneIoError::InvalidFormat {
                    message: "missing PLY magic header".to_string(),
                });
            }
            saw_magic = true;
            continue;
        }

        if let Some(rest) = trimmed.strip_prefix("format ") {
            header.format = match rest.trim() {
                "ascii 1.0" => PlyFormat::Ascii,
                "binary_little_endian 1.0" => PlyFormat::BinaryLittleEndian,
                other => {
                    return Err(SceneIoError::InvalidFormat {
                        message: format!("unsupported PLY format {other}"),
                    });
                }
            };
            continue;
        }

        if let Some(rest) = trimmed.strip_prefix("comment iterations ") {
            header.metadata.iterations = rest.trim().parse().unwrap_or(0);
        } else if let Some(rest) = trimmed.strip_prefix("comment final_loss ") {
            header.metadata.final_loss = rest.trim().parse().unwrap_or(0.0);
        } else if let Some(rest) = trimmed.strip_prefix("comment sh_degree ") {
            header.metadata.sh_degree = rest.trim().parse().unwrap_or(0);
            header.has_explicit_sh_degree = true;
        } else if let Some(rest) = trimmed.strip_prefix("comment SH degree: ") {
            header.metadata.sh_degree = rest.trim().parse().unwrap_or(header.metadata.sh_degree);
            header.has_explicit_sh_degree = true;
        } else if let Some(rest) = trimmed.strip_prefix("comment opacity_representation ") {
            header.opacity_representation = match rest.trim() {
                "probability" => Some(PlyOpacityRepresentation::Probability),
                "raw_logit" => Some(PlyOpacityRepresentation::RawLogit),
                _ => None,
            };
        } else if let Some(rest) = trimmed.strip_prefix("comment sh_coeff_layout ") {
            header.sh_coeff_layout = match rest.trim() {
                "interleaved" => Some(PlyShCoeffLayout::Interleaved),
                "channel_major" => Some(PlyShCoeffLayout::ChannelMajor),
                _ => None,
            };
        } else if trimmed.starts_with("element ") {
            let mut parts = trimmed.split_whitespace();
            let _ = parts.next();
            let name = parts.next().unwrap_or_default();
            let count = parts
                .next()
                .unwrap_or_default()
                .parse::<usize>()
                .unwrap_or(0);
            current_element = Some(name.to_string());
            if name == "vertex" {
                header.vertex_count = count;
            }
        } else if trimmed.starts_with("property ") && current_element.as_deref() == Some("vertex") {
            let parts: Vec<_> = trimmed.split_whitespace().collect();
            if parts.get(1) == Some(&"list") {
                return Err(SceneIoError::InvalidFormat {
                    message: "list vertex properties are not supported in splat PLY loader"
                        .to_string(),
                });
            }
            if parts.len() != 3 {
                return Err(SceneIoError::InvalidFormat {
                    message: format!("invalid property declaration: {trimmed}"),
                });
            }
            match parts[1] {
                "float" | "float32" => {}
                other => {
                    return Err(SceneIoError::InvalidFormat {
                        message: format!(
                            "unsupported vertex property type {other} in {}",
                            path.display()
                        ),
                    });
                }
            }
            header.vertex_properties.push(parts[2].to_string());
        } else if trimmed == "end_header" {
            return Ok((header, offset));
        }
    }

    Err(SceneIoError::InvalidFormat {
        message: "missing end_header in splat PLY".to_string(),
    })
}

#[cfg(feature = "gpu")]
fn find_property_index(properties: &[String], name: &str) -> Result<usize, SceneIoError> {
    properties
        .iter()
        .position(|property| property == name)
        .ok_or_else(|| SceneIoError::InvalidFormat {
            message: format!("missing required PLY property {name}"),
        })
}

#[cfg(feature = "gpu")]
fn build_vertex_field_map(properties: &[String]) -> Result<VertexFieldMap, SceneIoError> {
    let mut sh_rest = Vec::new();
    for (idx, property) in properties.iter().enumerate() {
        let Some(suffix) = property.strip_prefix("f_rest_") else {
            continue;
        };
        let order = suffix
            .parse::<usize>()
            .map_err(|_| SceneIoError::InvalidFormat {
                message: format!("invalid SH property name {property}"),
            })?;
        sh_rest.push((order, idx));
    }
    sh_rest.sort_by_key(|(order, _)| *order);
    for (expected, (actual, _)) in sh_rest.iter().enumerate() {
        if *actual != expected {
            return Err(SceneIoError::InvalidFormat {
                message: format!(
                    "f_rest properties must be contiguous from f_rest_0; expected f_rest_{expected}, found f_rest_{actual}"
                ),
            });
        }
    }

    Ok(VertexFieldMap {
        positions: [
            find_property_index(properties, "x")?,
            find_property_index(properties, "y")?,
            find_property_index(properties, "z")?,
        ],
        log_scales: [
            find_property_index(properties, "scale_0")?,
            find_property_index(properties, "scale_1")?,
            find_property_index(properties, "scale_2")?,
        ],
        opacity: find_property_index(properties, "opacity")?,
        rotations: [
            find_property_index(properties, "rot_0")?,
            find_property_index(properties, "rot_1")?,
            find_property_index(properties, "rot_2")?,
            find_property_index(properties, "rot_3")?,
        ],
        sh_dc: [
            find_property_index(properties, "f_dc_0")?,
            find_property_index(properties, "f_dc_1")?,
            find_property_index(properties, "f_dc_2")?,
        ],
        sh_rest: sh_rest.into_iter().map(|(_, idx)| idx).collect(),
    })
}

#[cfg(feature = "gpu")]
fn infer_sh_degree(
    explicit_degree: Option<usize>,
    sh_rest_count: usize,
) -> Result<usize, SceneIoError> {
    if let Some(degree) = explicit_degree {
        if degree > 3 {
            return Err(SceneIoError::InvalidFormat {
                message: format!(
                    "unsupported sh_degree {degree} in splat loader; current path supports up to degree 3"
                ),
            });
        }
        let expected = sh_coeff_count_for_degree(degree)
            .saturating_sub(1)
            .saturating_mul(3);
        if sh_rest_count != expected {
            return Err(SceneIoError::InvalidFormat {
                message: format!(
                    "sh_degree {degree} requires {expected} f_rest properties, found {sh_rest_count}"
                ),
            });
        }
        return Ok(degree);
    }
    match sh_rest_count {
        0 => Ok(0),
        9 => Ok(1),
        24 => Ok(2),
        45 => Ok(3),
        _ => Err(SceneIoError::InvalidFormat {
            message: format!(
                "could not infer supported SH degree from {sh_rest_count} f_rest properties"
            ),
        }),
    }
}

#[cfg(feature = "gpu")]
fn append_vertex_values(
    values: &[f32],
    field_map: &VertexFieldMap,
    sh_degree: usize,
    opacity_representation: PlyOpacityRepresentation,
    sh_layout: PlyShCoeffLayout,
    positions: &mut Vec<f32>,
    log_scales: &mut Vec<f32>,
    rotations: &mut Vec<f32>,
    opacity_logits: &mut Vec<f32>,
    sh_coeffs: &mut Vec<f32>,
) -> Result<(), SceneIoError> {
    positions.extend(field_map.positions.iter().map(|&idx| values[idx]));
    log_scales.extend(field_map.log_scales.iter().map(|&idx| values[idx]));
    rotations.extend(field_map.rotations.iter().map(|&idx| values[idx]));
    opacity_logits.push(opacity_value_to_logit(
        values[field_map.opacity],
        opacity_representation,
    ));
    sh_coeffs.extend(field_map.sh_dc.iter().map(|&idx| values[idx]));

    let sh_rest_to_keep = sh_coeff_count_for_degree(sh_degree)
        .saturating_sub(1)
        .saturating_mul(3);
    if sh_rest_to_keep > 0 {
        let mut sh_rest = vec![0.0f32; sh_rest_to_keep];
        for (dst, src_idx) in field_map.sh_rest.iter().take(sh_rest_to_keep).enumerate() {
            sh_rest[dst] = values[*src_idx];
        }
        match sh_layout {
            PlyShCoeffLayout::Interleaved => sh_coeffs.extend_from_slice(&sh_rest),
            PlyShCoeffLayout::ChannelMajor => {
                sh_coeffs.extend(channel_major_sh_rest_to_interleaved(&sh_rest))
            }
        }
    }

    Ok(())
}

#[cfg(feature = "gpu")]
pub fn save_splats_ply(
    path: &Path,
    splats: &crate::core::HostSplats,
    metadata: &SplatMetadata,
) -> Result<(), SceneIoError> {
    splats
        .validate()
        .map_err(|err| SceneIoError::InvalidFormat {
            message: err.to_string(),
        })?;

    if splats.sh_degree() > 3 {
        return Err(SceneIoError::InvalidFormat {
            message: format!(
                "unsupported sh_degree {} in splat writer; current path supports up to degree 3",
                splats.sh_degree()
            ),
        });
    }
    if metadata.sh_degree != splats.sh_degree() {
        return Err(SceneIoError::InvalidFormat {
            message: format!(
                "metadata sh_degree {} does not match scene sh_degree {}",
                metadata.sh_degree,
                splats.sh_degree()
            ),
        });
    }
    if metadata.gaussian_count != 0 && metadata.gaussian_count != splats.len() {
        return Err(SceneIoError::InvalidFormat {
            message: format!(
                "metadata gaussian_count {} does not match scene count {}",
                metadata.gaussian_count,
                splats.len()
            ),
        });
    }

    let file = File::create(path).map_err(|source| SceneIoError::Write {
        path: path.display().to_string(),
        source,
    })?;
    let mut writer = BufWriter::new(file);
    let sh_rest_count = sh_coeff_count_for_degree(splats.sh_degree())
        .saturating_sub(1)
        .saturating_mul(3);
    write_ply_header(&mut writer, path, metadata, splats.len(), sh_rest_count)?;

    let view = splats.as_view();
    let sh_coeff_row_width = sh_coeff_count_for_degree(view.sh_degree) * 3;

    for idx in 0..splats.len() {
        let position_base = idx * 3;
        let rotation_base = idx * 4;
        let sh_base = idx * sh_coeff_row_width;
        let sh_coeffs = &view.sh_coeffs[sh_base..sh_base + sh_coeff_row_width];

        write!(
            writer,
            "{} {} {} 0 0 0 {} {} {} ",
            view.positions[position_base],
            view.positions[position_base + 1],
            view.positions[position_base + 2],
            sh_coeffs[0],
            sh_coeffs[1],
            sh_coeffs[2],
        )
        .map_err(|source| SceneIoError::Write {
            path: path.display().to_string(),
            source,
        })?;

        let sh_rest = &sh_coeffs[3..];
        let sh_rest_channel_major = interleaved_sh_rest_to_channel_major(sh_rest);
        for value in sh_rest_channel_major {
            write!(writer, "{} ", value).map_err(|source| SceneIoError::Write {
                path: path.display().to_string(),
                source,
            })?;
        }

        writeln!(
            writer,
            "{} {} {} {} {} {} {} {}",
            view.opacity_logits[idx],
            view.log_scales[position_base],
            view.log_scales[position_base + 1],
            view.log_scales[position_base + 2],
            view.rotations[rotation_base],
            view.rotations[rotation_base + 1],
            view.rotations[rotation_base + 2],
            view.rotations[rotation_base + 3],
        )
        .map_err(|source| SceneIoError::Write {
            path: path.display().to_string(),
            source,
        })?;
    }

    Ok(())
}

#[cfg(feature = "gpu")]
pub fn save_splats_splat(
    path: &Path,
    splats: &crate::core::HostSplats,
    _metadata: &SplatMetadata,
) -> Result<(), SceneIoError> {
    splats
        .validate()
        .map_err(|err| SceneIoError::InvalidFormat {
            message: err.to_string(),
        })?;

    let file = File::create(path).map_err(|source| SceneIoError::Write {
        path: path.display().to_string(),
        source,
    })?;
    let mut writer = BufWriter::new(file);

    for idx in 0..splats.len() {
        for value in splats.position(idx) {
            writer
                .write_all(&value.to_le_bytes())
                .map_err(|source| SceneIoError::Write {
                    path: path.display().to_string(),
                    source,
                })?;
        }
        for value in splats.scale(idx) {
            writer
                .write_all(&value.to_le_bytes())
                .map_err(|source| SceneIoError::Write {
                    path: path.display().to_string(),
                    source,
                })?;
        }

        let rgb = splats.rgb_color(idx);
        let color = [
            normalized_to_u8(rgb[0]),
            normalized_to_u8(rgb[1]),
            normalized_to_u8(rgb[2]),
            normalized_to_u8(splats.opacity(idx)),
        ];
        writer
            .write_all(&color)
            .map_err(|source| SceneIoError::Write {
                path: path.display().to_string(),
                source,
            })?;

        let rotation = normalized_quaternion(splats.rotation(idx));
        let rotation_bytes = [
            quaternion_component_to_u8(rotation[0]),
            quaternion_component_to_u8(rotation[1]),
            quaternion_component_to_u8(rotation[2]),
            quaternion_component_to_u8(rotation[3]),
        ];
        writer
            .write_all(&rotation_bytes)
            .map_err(|source| SceneIoError::Write {
                path: path.display().to_string(),
                source,
            })?;
    }

    Ok(())
}

#[cfg(feature = "gpu")]
pub fn save_splats(
    path: &Path,
    splats: &crate::core::HostSplats,
    metadata: &SplatMetadata,
) -> Result<(), SceneIoError> {
    match splat_file_format(path)? {
        SplatFileFormat::Ply => save_splats_ply(path, splats, metadata),
        SplatFileFormat::Splat => save_splats_splat(path, splats, metadata),
    }
}

#[cfg(feature = "gpu")]
pub fn load_splats_ply(
    path: &Path,
) -> Result<(crate::core::HostSplats, SplatMetadata), SceneIoError> {
    let bytes = std::fs::read(path).map_err(|source| SceneIoError::Read {
        path: path.display().to_string(),
        source,
    })?;
    let (header, body_offset) = parse_ply_header(&bytes, path)?;
    let field_map = build_vertex_field_map(&header.vertex_properties)?;

    let mut metadata = header.metadata;
    metadata.sh_degree = infer_sh_degree(
        if header.has_explicit_sh_degree {
            Some(metadata.sh_degree)
        } else {
            None
        },
        field_map.sh_rest.len(),
    )?;

    if metadata.sh_degree > 3 {
        return Err(SceneIoError::InvalidFormat {
            message: format!(
                "unsupported sh_degree {} in splat loader; current path supports up to degree 3",
                metadata.sh_degree
            ),
        });
    }

    let opacity_representation = header
        .opacity_representation
        .unwrap_or(PlyOpacityRepresentation::RawLogit);
    let sh_layout = header
        .sh_coeff_layout
        .unwrap_or(PlyShCoeffLayout::ChannelMajor);

    let mut positions = Vec::new();
    let mut log_scales = Vec::new();
    let mut rotations = Vec::new();
    let mut opacity_logits = Vec::new();
    let mut sh_coeffs = Vec::new();

    match header.format {
        PlyFormat::Ascii => {
            let body = std::str::from_utf8(&bytes[body_offset..])
                .map_err(|err| SceneIoError::Parse(err.to_string()))?;
            for line in body.lines() {
                let trimmed = line.trim();
                if trimmed.is_empty() {
                    continue;
                }

                let values: Vec<f32> = trimmed
                    .split_whitespace()
                    .map(|value| value.parse::<f32>())
                    .collect::<Result<Vec<_>, _>>()
                    .map_err(|err| SceneIoError::Parse(err.to_string()))?;
                if values.len() != header.vertex_properties.len() {
                    return Err(SceneIoError::InvalidFormat {
                        message: format!(
                            "expected {} values per vertex in splat PLY, got {}",
                            header.vertex_properties.len(),
                            values.len()
                        ),
                    });
                }
                append_vertex_values(
                    &values,
                    &field_map,
                    metadata.sh_degree,
                    opacity_representation,
                    sh_layout,
                    &mut positions,
                    &mut log_scales,
                    &mut rotations,
                    &mut opacity_logits,
                    &mut sh_coeffs,
                )?;
            }
        }
        PlyFormat::BinaryLittleEndian => {
            let property_count = header.vertex_properties.len();
            let row_bytes = property_count
                .checked_mul(std::mem::size_of::<f32>())
                .ok_or_else(|| SceneIoError::InvalidFormat {
                    message: "vertex row byte width overflow while reading PLY".to_string(),
                })?;
            let expected_bytes = header.vertex_count.checked_mul(row_bytes).ok_or_else(|| {
                SceneIoError::InvalidFormat {
                    message: "vertex byte size overflow while reading PLY".to_string(),
                }
            })?;
            let body = &bytes[body_offset..];
            if body.len() < expected_bytes {
                return Err(SceneIoError::InvalidFormat {
                    message: format!(
                        "binary PLY truncated: expected at least {expected_bytes} bytes, got {}",
                        body.len()
                    ),
                });
            }

            let mut cursor = 0usize;
            let mut values = vec![0.0f32; property_count];
            for _ in 0..header.vertex_count {
                for value in &mut values {
                    let chunk: [u8; 4] = body[cursor..cursor + 4].try_into().map_err(|_| {
                        SceneIoError::InvalidFormat {
                            message: "failed to decode binary PLY float".to_string(),
                        }
                    })?;
                    *value = f32::from_le_bytes(chunk);
                    cursor += 4;
                }
                append_vertex_values(
                    &values,
                    &field_map,
                    metadata.sh_degree,
                    opacity_representation,
                    sh_layout,
                    &mut positions,
                    &mut log_scales,
                    &mut rotations,
                    &mut opacity_logits,
                    &mut sh_coeffs,
                )?;
            }
        }
    }

    let parsed_vertices = opacity_logits.len();
    if parsed_vertices != header.vertex_count {
        return Err(SceneIoError::InvalidFormat {
            message: format!(
                "vertex count mismatch: header {}, parsed {}",
                header.vertex_count, parsed_vertices
            ),
        });
    }

    if metadata.gaussian_count == 0 {
        metadata.gaussian_count = parsed_vertices;
    }

    let splats = crate::core::HostSplats::from_components(
        positions,
        log_scales,
        rotations,
        opacity_logits,
        sh_coeffs,
        metadata.sh_degree,
    )
    .map_err(|err| SceneIoError::InvalidFormat {
        message: err.to_string(),
    })?;

    Ok((splats, metadata))
}

#[cfg(feature = "gpu")]
pub fn load_splats_splat(
    path: &Path,
) -> Result<(crate::core::HostSplats, SplatMetadata), SceneIoError> {
    const ROW_BYTES: usize = 32;

    let bytes = std::fs::read(path).map_err(|source| SceneIoError::Read {
        path: path.display().to_string(),
        source,
    })?;
    if bytes.len() % ROW_BYTES != 0 {
        return Err(SceneIoError::InvalidFormat {
            message: format!(
                "invalid .splat byte length {}; expected a multiple of {ROW_BYTES}",
                bytes.len()
            ),
        });
    }

    let row_count = bytes.len() / ROW_BYTES;
    let mut positions = Vec::with_capacity(row_count * 3);
    let mut log_scales = Vec::with_capacity(row_count * 3);
    let mut rotations = Vec::with_capacity(row_count * 4);
    let mut opacity_logits = Vec::with_capacity(row_count);
    let mut sh_coeffs = Vec::with_capacity(row_count * 3);

    for row in bytes.chunks_exact(ROW_BYTES) {
        for idx in 0..3 {
            positions.push(read_le_f32(row, idx * 4)?);
        }
        for idx in 0..3 {
            let scale = read_le_f32(row, 12 + idx * 4)?;
            log_scales.push(scale.max(1e-8).ln());
        }

        let rgb = [
            row[24] as f32 / 255.0,
            row[25] as f32 / 255.0,
            row[26] as f32 / 255.0,
        ];
        sh_coeffs.extend(rgb.map(rgb_to_sh0_value));
        opacity_logits.push(opacity_to_logit(row[27] as f32 / 255.0));

        let rotation = normalized_quaternion([
            u8_to_quaternion_component(row[28]),
            u8_to_quaternion_component(row[29]),
            u8_to_quaternion_component(row[30]),
            u8_to_quaternion_component(row[31]),
        ]);
        rotations.extend_from_slice(&rotation);
    }

    let metadata = SplatMetadata {
        iterations: 0,
        final_loss: 0.0,
        gaussian_count: row_count,
        sh_degree: 0,
    };
    let splats = crate::core::HostSplats::from_components(
        positions,
        log_scales,
        rotations,
        opacity_logits,
        sh_coeffs,
        0,
    )
    .map_err(|err| SceneIoError::InvalidFormat {
        message: err.to_string(),
    })?;

    Ok((splats, metadata))
}

#[cfg(feature = "gpu")]
pub fn load_splats(path: &Path) -> Result<(crate::core::HostSplats, SplatMetadata), SceneIoError> {
    match splat_file_format(path)? {
        SplatFileFormat::Ply => load_splats_ply(path),
        SplatFileFormat::Splat => load_splats_splat(path),
    }
}

/// Verify that a lossless scene round-trip preserved all components and metadata.
#[cfg(feature = "gpu")]
pub fn verify_lossless_roundtrip(
    expected: &crate::core::HostSplats,
    expected_metadata: &SplatMetadata,
    actual: &crate::core::HostSplats,
    actual_metadata: &SplatMetadata,
) -> Result<(), SceneIoError> {
    expected
        .validate()
        .map_err(|err| SceneIoError::InvalidFormat {
            message: format!("invalid expected splats: {err}"),
        })?;
    actual
        .validate()
        .map_err(|err| SceneIoError::InvalidFormat {
            message: format!("invalid round-trip splats: {err}"),
        })?;

    if expected_metadata != actual_metadata {
        return Err(SceneIoError::InvalidFormat {
            message: format!(
                "round-trip metadata mismatch: expected {expected_metadata:?}, got {actual_metadata:?}"
            ),
        });
    }

    let expected = expected.as_view();
    let actual = actual.as_view();
    for (name, matches) in [
        ("positions", expected.positions == actual.positions),
        ("log_scales", expected.log_scales == actual.log_scales),
        ("rotations", expected.rotations == actual.rotations),
        (
            "opacity_logits",
            expected.opacity_logits == actual.opacity_logits,
        ),
        ("sh_coeffs", expected.sh_coeffs == actual.sh_coeffs),
        ("sh_degree", expected.sh_degree == actual.sh_degree),
    ] {
        if !matches {
            return Err(SceneIoError::InvalidFormat {
                message: format!("round-trip {name} mismatch"),
            });
        }
    }
    Ok(())
}

#[cfg(feature = "gpu")]
fn read_le_f32(bytes: &[u8], offset: usize) -> Result<f32, SceneIoError> {
    let chunk: [u8; 4] = bytes
        .get(offset..offset + 4)
        .and_then(|chunk| chunk.try_into().ok())
        .ok_or_else(|| SceneIoError::InvalidFormat {
            message: "truncated .splat float field".to_string(),
        })?;
    Ok(f32::from_le_bytes(chunk))
}

#[cfg(feature = "gpu")]
fn normalized_to_u8(value: f32) -> u8 {
    (value.clamp(0.0, 1.0) * 255.0).round() as u8
}

#[cfg(feature = "gpu")]
fn quaternion_component_to_u8(value: f32) -> u8 {
    ((value.clamp(-1.0, 1.0) * 128.0) + 128.0)
        .round()
        .clamp(0.0, 255.0) as u8
}

#[cfg(feature = "gpu")]
fn u8_to_quaternion_component(value: u8) -> f32 {
    (value as f32 - 128.0) / 128.0
}

#[cfg(feature = "gpu")]
fn normalized_quaternion(rotation: [f32; 4]) -> [f32; 4] {
    let length_sq = rotation.iter().map(|value| value * value).sum::<f32>();
    if !length_sq.is_finite() || length_sq <= 1e-12 {
        return [1.0, 0.0, 0.0, 0.0];
    }
    let inv_length = length_sq.sqrt().recip();
    [
        rotation[0] * inv_length,
        rotation[1] * inv_length,
        rotation[2] * inv_length,
        rotation[3] * inv_length,
    ]
}

#[cfg(all(test, feature = "gpu"))]
mod tests {
    use super::*;
    use crate::core::HostSplats;

    fn degree_one_splats() -> HostSplats {
        HostSplats::from_components(
            vec![1.25, -2.5, 3.75, -4.0, 5.5, -6.25],
            vec![-1.0, -0.5, 0.25, 0.0, 0.5, 1.0],
            vec![1.0, 0.0, 0.0, 0.0, 0.5, 0.5, 0.5, 0.5],
            vec![-0.75, 1.25],
            (0..24).map(|value| value as f32 * 0.125 - 1.0).collect(),
            1,
        )
        .unwrap()
    }

    #[test]
    fn ply_roundtrip_preserves_every_component_and_metadata() {
        let temp = tempfile::tempdir().unwrap();
        let path = temp.path().join("scene.ply");
        let splats = degree_one_splats();
        let metadata = SplatMetadata {
            iterations: 123,
            final_loss: 0.03125,
            gaussian_count: splats.len(),
            sh_degree: splats.sh_degree(),
        };

        save_splats_ply(&path, &splats, &metadata).unwrap();
        let (loaded, loaded_metadata) = load_splats_ply(&path).unwrap();

        verify_lossless_roundtrip(&splats, &metadata, &loaded, &loaded_metadata).unwrap();
    }

    #[test]
    fn lossless_roundtrip_verifier_rejects_component_changes() {
        let expected = degree_one_splats();
        let view = expected.as_view();
        let mut positions = view.positions.to_vec();
        positions[0] += 0.5;
        let changed = HostSplats::from_components(
            positions,
            view.log_scales.to_vec(),
            view.rotations.to_vec(),
            view.opacity_logits.to_vec(),
            view.sh_coeffs.to_vec(),
            view.sh_degree,
        )
        .unwrap();
        let metadata = expected.to_splat_metadata(3, 0.25);

        let err = verify_lossless_roundtrip(&expected, &metadata, &changed, &metadata).unwrap_err();
        assert!(err.to_string().contains("positions"));
    }

    #[test]
    fn ply_writer_rejects_metadata_that_disagrees_with_scene() {
        let temp = tempfile::tempdir().unwrap();
        let path = temp.path().join("scene.ply");
        let splats = degree_one_splats();
        let metadata = SplatMetadata {
            gaussian_count: splats.len(),
            sh_degree: 0,
            ..Default::default()
        };

        let err = save_splats_ply(&path, &splats, &metadata).unwrap_err();
        assert!(err.to_string().contains("metadata sh_degree"));
    }

    #[test]
    fn explicit_sh_degree_must_match_f_rest_property_count() {
        let err = infer_sh_degree(Some(1), 45).unwrap_err();
        assert!(err.to_string().contains("sh_degree 1 requires 9 f_rest"));
    }

    #[test]
    fn malformed_ply_fixture_with_mismatched_degree_is_rejected() {
        let temp = tempfile::tempdir().unwrap();
        let path = temp.path().join("mismatched-degree.ply");
        std::fs::write(
            &path,
            concat!(
                "ply\n",
                "format ascii 1.0\n",
                "comment sh_degree 1\n",
                "element vertex 1\n",
                "property float x\nproperty float y\nproperty float z\n",
                "property float f_dc_0\nproperty float f_dc_1\nproperty float f_dc_2\n",
                "property float opacity\n",
                "property float scale_0\nproperty float scale_1\nproperty float scale_2\n",
                "property float rot_0\nproperty float rot_1\n",
                "property float rot_2\nproperty float rot_3\n",
                "end_header\n",
                "0 0 1 0 0 0 0 0 0 1 0 0 0 0\n",
            ),
        )
        .unwrap();

        let err = load_splats_ply(&path).unwrap_err();
        assert!(err.to_string().contains("sh_degree 1 requires 9 f_rest"));
    }

    #[test]
    fn f_rest_properties_must_be_contiguously_numbered() {
        let mut properties = vec![
            "x", "y", "z", "scale_0", "scale_1", "scale_2", "opacity", "rot_0", "rot_1", "rot_2",
            "rot_3", "f_dc_0", "f_dc_1", "f_dc_2", "f_rest_0", "f_rest_2",
        ]
        .into_iter()
        .map(str::to_string)
        .collect::<Vec<_>>();
        properties.sort();

        let err = build_vertex_field_map(&properties).unwrap_err();
        assert!(err.to_string().contains("contiguous"));
    }

    #[test]
    fn artifact_fidelity_distinguishes_lossless_ply_from_legacy_splat() {
        assert_eq!(
            splat_artifact_fidelity(Path::new("scene.ply")).unwrap(),
            SplatArtifactFidelity::Lossless
        );
        assert_eq!(
            splat_artifact_fidelity(Path::new("scene.splat")).unwrap(),
            SplatArtifactFidelity::LossyLegacy
        );
    }

    #[test]
    fn malformed_legacy_splat_row_is_rejected() {
        let temp = tempfile::tempdir().unwrap();
        let path = temp.path().join("truncated.splat");
        std::fs::write(&path, [0_u8; 31]).unwrap();

        let err = load_splats_splat(&path).unwrap_err();
        assert!(err.to_string().contains("multiple of 32"));
    }
}
